export const FETCH_ADMIN_NAME = 'FETCH_ADMIN_NAME';

export const FETCH_BOOKING_DETAILS = 'FETCH_BOOKING_DETAILS';
export const CANCEL_BOOKING = 'CANCEL_BOOKING';
export const FETCH_ALL_BOOKINGS = 'FETCH_ALL_BOOKINGS';

export const FETCH_ROOM_DETAILS = 'FETCH_ROOM_DETAILS';
export const UPDATE_ROOM = 'UPDATE_ROOM';
export const DELETE_ROOM = 'DELETE_ROOM';
export const FETCH_ALL_ROOMS = 'FETCH_ALL_ROOMS';
export const ADD_ROOM = 'ADD_ROOM';
export const FETCH_ROOM_TYPES = 'FETCH_ROOM_TYPES';